# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
#   branches:
#     include:
#       - main # or your deployment branch

# pool:
#   vmImage: "ubuntu-latest"

# steps:
#   - task: NodeTool@0
#     inputs:
#       versionSpec: "18.x" # or whatever version you use
#     displayName: "Use Node.js"

#   - script: npm install
#     displayName: "Install dependencies"

#   - script: npm run build
#     displayName: "Build React App"

#   - task: AzureWebApp@1
#     inputs:
#       azureSubscription: "chatbot-service-connection" # service connection name
#       appName: "genie-bot-frontend" # Azure App Service name
#       package: "$(System.DefaultWorkingDirectory)/build" # React build output

trigger:
  branches:
    include:
      - main # Or your deployment branch

pool:
  vmImage: "ubuntu-latest"

variables:
  appName: "genie-bot-frontend"
  packageDir: "build"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x" # Match your React Node version
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build
    displayName: "Install dependencies and build React app"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "chatbot-service-connection"
      appType: "webAppLinux"
      appName: "$(appName)"
      package: "$(packageDir)"
    displayName: "Deploy to Azure Web App"
