trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  appName: "genie-bot-frontend"
  packageDir: "dist" # Vite uses dist/ instead of build/

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build  # Ensure you're using the default Vite build script
    displayName: "Install dependencies and build Vite app"
    env:
      VITE_API_BASE_URL: "https://genie-bot-backend-dev.azurewebsites.net/api/v1"

  - script: |
      echo "Listing root and dist folder"
      ls -la
      ls -la dist  # Check if the dist/ folder exists
    displayName: "Debug: check dist output"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(packageDir)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/vite-app.zip"
      replaceExistingArchive: true
    displayName: "Archive Vite build output"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "chatbot-service-connection"
      appType: "webAppLinux"
      appName: "$(appName)"
      slotName: "dev"
      package: "$(Build.ArtifactStagingDirectory)/vite-app.zip"
    displayName: "Deploy to Azure Web App"
